# Global configurations
# http://prospector.landscape.io/en/master/profiles.html
# -----------------------------------------------------------------------------

strictness: verylow
doc-warnings: false
member-warnings: true

# Without this setting, Prospector incorrectly tries to load the Django plugin,
# which raised an Exception
autodetect: false

# Module-specific configurations
# http://prospector.landscape.io/en/master/supported_tools.html
# -----------------------------------------------------------------------------

# https://www.pylint.org/
pylint:
  run: true

# https://pep8.readthedocs.io/
pep8:
  run: true

# https://launchpad.net/pyflakes
pyflakes:
  run: true

# https://github.com/PyCQA/mccabe
mccabe:
  run: true

# https://github.com/landscapeio/dodgy
dodgy:
  run: true

# https://github.com/PyCQA/pydocstyle
pep257:
  run: true

# https://github.com/regebro/pyroma
pyroma:
  run: true

# https://github.com/jendrikseipp/vulture
vulture:
  run: true

# Use pyflakes instead
# https://github.com/timothycrosley/frosted
frosted:
  run: false

# This project is not ready for static typing
# https://github.com/python/mypy
mypy:
  run: false

# https://github.com/PyCQA/bandit
bandit:
  run: true

# Internal check to validate this file
profile-validator:
  run: true
