pull_request_rules:
  - name: Ready to merge
    conditions:
      and:
        - label=ready-to-merge
        - check-success~=^Build
        - check-success~=^GitGuardian
    actions:
      merge:
        method: rebase
        rebase_fallback: null
