pull_request_rules:
  - name: Ready to merge
    conditions:
      - label=ready-to-merge
      - check-success~=Checks
      - check-success~=Telemetry
      - check-success~=GitGuardian
    actions:
      merge:
        method: rebase
        rebase_fallback: null
