pull_request_rules:
  - name: Ready to merge
    conditions:
      - and:
          - label=ready-to-merge
          - check-success~=^Checks
          - check-success~=^GitGuardian
      - or:
          - check-success~=^((Header|Redirect) rules|Mixed content)
          - check-skipped~=^((Header|Redirect) rules|Mixed content)
          - check-neutral~=^((Header|Redirect) rules|Mixed content)
    actions:
      merge:
        method: rebase
        rebase_fallback: null
