root: ./gitbook/cmp/

redirects:
  amazon-web-services/add-your-amazon-web-services-iam-role: ./amazon-web-services/link-account.md
  amazon-web-services/aws-ro-access: ./tickets/aws-access.md
  dashboards/aws-finops-dashboard: ./dashboards/aws-lens.md
  flexible-reservations/flexri-faq: ./flexsave/overview.md
  flexible-reservations/flexri-regions: ./flexsave/aws.md
  flexible-reservations/flexri: ./flexsave/overview.md
  flexsave-aws/faq: ./flexsave/overview.md
  flexsave-aws/flexsave-regions: ./flexsave/aws.md
  flexsave-aws/overview: ./flexsave/overview.md
  general/login: ./general/log-in.md
  general/sharing-feedback-and-feature-requests: ./general/sharing-feedback.md
  notifications/cloud-credits: ./general/profile.md
  notifications/default-notifications: ./general/profile.md
  notifications/default: ./general/profile.md
  notifications/managing-alerts-in-shared-slack-channels: ./general/slack.md
  notifications/new-invoices: ./general/profile.md
  notifications/payment-reminders: ./general/profile.md
  notifications/slack: ./general/slack.md
  perks/perks: ./services/perks.md
  tickets/aws-access: ./services/consulting-support/aws-access.md
  tickets/aws-ro-access: ./services/consulting-support/aws-access.md
  tickets/cloud-infrastructure-known-issues: ./services/consulting-support/cloud-incidents.md
  tickets/escalating-support-requests: ./services/consulting-support/escalate.md
  tickets/gcp-access: ./services/consulting-support/gcp-access.md
  tickets/gcp-ro-access: ./services/consulting-support/gcp-access.md
  tickets/manage-default-email-cc: ./services/consulting-support/manage-default-email-cc.md
  tickets/open-a-new-support-request: ./services/consulting-support/README.md
  tickets/ticket-sharing: ./services/consulting-support/ticket-sharing.md
