name: CICD

on:
  pull_request:
  push:
    branches:
      - main
      - feature/fssa

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/doitintl/docops/devcontainer:main
    steps:
      - uses: actions/checkout@v2
      - run: make check
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/doitintl/docops/devcontainer:main
    steps:
      - uses: actions/checkout@v2
      - run: make build

  # TODO: Trigger Netlify build if check and build succeed

  telemetry:
    name: Telemetry
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/doitintl/docops/devcontainer:main
    steps:
      - uses: actions/checkout@v2
      - run: make telemetry
      - uses: crazy-max/ghaction-github-status@v2
        with:
          pages_threshold: major_outage
      - uses: crazy-max/ghaction-github-pages@v2
        if: success() && github.event_name != 'pull_request'
        with:
          target_branch: gh-pages
          build_dir: gh-pages
          keep_history: true
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  notification:
    name: Notification
    needs:
      - check
      - build
      - telemetry
    if: |
      always()
      && github.event_name != 'pull_request'
      && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: martialonline/workflow-status@v2
        id: check
      - uses: ravsamhq/notify-slack-action@v1
        env:
          STATUS: '{workflow} workflow <{run_url}|{status_message}>'
          COMMIT: for commit `<{commit_url}|{commit_sha}>`
          BRANCH: on branch `${{ github.ref_name }}`
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ steps.check.outputs.status }}
          notification_title: ''
          message_format: ${{ env.STATUS }} ${{ env.COMMIT }} ${{ env.BRANCH }}
          footer: <{repo_url}|{repo}>
          notify_when: success,warning,failure
