name: Commit

on:
  pull_request:
  push:
    branches:
      - main
      - feature/fssa

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/doitintl/docops/devcontainer:main
    steps:
      - uses: actions/checkout@v2
      - run: make check

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/doitintl/docops/devcontainer:main
    steps:
      - uses: actions/checkout@v2
      - run: make build

  # TODO: Trigger Netlify deployment if check and build succeed

  # TODO: Use custom Python script to handle repository notifications (with the
  # goal being to switch to a single updatable message per commit)

  notification:
    name: Notification
    needs:
      - check
      - build
    if: |
      always()
      && github.event_name != 'pull_request'
      && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: martialonline/workflow-status@v2
        id: check
      - uses: ravsamhq/notify-slack-action@v1
        env:
          STATUS: '{workflow} workflow <{run_url}|{status_message}>'
          COMMIT: for `<{commit_url}|{commit_sha}>`
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ steps.check.outputs.status }}
          notification_title: ''
          message_format: ${{ env.STATUS }} ${{ env.COMMIT }}
          footer: '<{repo_url}|{repo}>'
          notify_when: success,warning,failure
