name: Cron

on:
  schedule:
    # Run at 06:00 every Saturday
    - cron: '0 6 * * 6'

jobs:
  link-check:
    name: Link check
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/doitintl/docops/devcontainer:main
    env:
      GIT_NAME: DocsBot
      GIT_EMAIL: 105730821+doitintl-docsbot@users.noreply.github.com
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DOCSBOT_PAT }}
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      # Invalidate cache
      - run: rm -f .brockdb
      # Rebuild cache
      - run: make brok
      # Silence Git warning
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: .brokdb
          commit_user_name: ${{ secrets.GIT_NAME }}
          commit_user_email: ${{ secrets.GIT_EMAIL }}
          commit_message: Update link check status cache

  # TODO: Use custom Python script to handle repository notifications (with the
  # goal being to switch to a single updatable message per commit)

  notification:
    name: Notification
    needs: link-check
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: martialonline/workflow-status@v3
        id: check
      - uses: ravsamhq/notify-slack-action@v1
        env:
          STATUS: '{workflow} workflow <{run_url}|{status_message}>'
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ steps.check.outputs.status }}
          notification_title: ''
          message_format: ${{ env.STATUS }}
          footer: '<{repo_url}|{repo}>'
          notify_when: success,warning,failure
