name: Deployment

on:
  repository_dispatch:
    types:
      - deploy_started
      - deploy_failed
      - deploy_succeeded

jobs:
  crawl:
    name: Crawl
    if: github.event.action == 'deploy_succeeded'
    runs-on: ubuntu-latest
    env:
      DEPLOY_URL: '${{ github.event.client_payload.deploy_url }}'
      BRANCH: '${{ github.event.client_payload.branch }}'
    steps:
      - uses: actions/checkout@v2
      - run: |
          cat .docops/algolia/template.json |
          jq '.index_name = "${{ env.BRANCH }}"' |
          jq '.start_urls = ["${{ env.DEPLOY_URL }}/"]' |
          jq '.sitemap_urls = ["${{ env.DEPLOY_URL }}/sitemap.xml"]' \
          > algolia.json
      - run: |
          echo "::set-output name=config::$(cat algolia.json | jq -r tostring)"
        id: env
      - uses: signcl/docsearch-scraper-action@master
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          CONFIG: ${{ steps.env.outputs.config }}

  # TODO: Use custom Python script to handle repository notifications (with the
  # goal being to switch to a single updatable message per commit)

  notification:
    name: Notification
    needs:
      - crawl
    if: |
      always()
      && github.event.client_payload.branch == 'main'
    runs-on: ubuntu-latest
    env:
      DEPLOY_URL: '${{ github.event.client_payload.deploy_url }}'
    steps:
      - uses: actions/checkout@v2
      - uses: martialonline/workflow-status@v2
        id: check
      - uses: ravsamhq/notify-slack-action@v1
        env:
          STATUS: '{workflow} workflow <{run_url}|{status_message}>'
          DEPLOYMENT: for ${{ env.DEPLOY_URL }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ steps.check.outputs.status }}
          notification_title: ''
          message_format: ${{ env.STATUS }} ${{ env.DEPLOYMENT }}
          footer: '<{repo_url}|{repo}>'
          notify_when: success,warning,failure
