name: Dispatch

on:
  repository_dispatch:
    types:
      - deployment

jobs:
  crawl:
    name: Crawl
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.event.client_payload.branch }}
      DEPLOY_URL: ${{ github.event.client_payload.deploy_url }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          cat .docops/algolia/template.json |
          jq '.index_name = "${{ env.BRANCH }}"' |
          jq '.start_urls = ["${{ env.DEPLOY_URL }}/"]' |
          jq '.sitemap_urls = ["${{ env.DEPLOY_URL }}/sitemap.xml"]' \
          > algolia.json
      - run: cat algolia.json
      - run: echo "::set-output name=config::$(cat algolia.json | jq -r tostring)"
        id: env

      # - uses: darrenjennings/algolia-docsearch-action@master
      #   with:
      #     algolia_application_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
      #     algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
      #     file: 'algolia.json'

      - uses: signcl/docsearch-scraper-action@master
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          CONFIG: ${{ steps.env.outputs.config }}
